=== shmuelp/asiddur/tools/asiddur-tefilla-annotated.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary indentification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/asiddur-tefilla-annotated.dtd

-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT asiddur-annotated (text|toc)*>
<!ATTLIST asiddur-annotated
    format CDATA #FIXED "0.1"
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT toc (tefillot|texts)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT tefillot (tefilla)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT tefilla (name)*>
<!ATTLIST tefilla
    target IDREF #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
    lang CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT texts (text-header)*>

<!ELEMENT text-header EMPTY>
<!ATTLIST text-header
    length CDATA #REQUIRED
    name ID #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT text (#PCDATA|include|navmark|p|br|if)*>
<!ATTLIST text
    length CDATA #REQUIRED
    name IDREF #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT if (#PCDATA|get|set|include|p|function|br|navmark|if|else)*>
<!ATTLIST if
    variable CDATA #IMPLIED
    day CDATA #IMPLIED
    month CDATA #IMPLIED
    or CDATA #IMPLIED
    length CDATA #REQUIRED
    function CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT else EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT br EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT navmark EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT function EMPTY>
<!ATTLIST function
    name CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT p EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT include EMPTY>
<!ATTLIST include
    target IDREF #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT set (#PCDATA)>
<!ATTLIST set
    length CDATA #REQUIRED
    slot CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT get EMPTY>
<!ATTLIST get
    slot CDATA #REQUIRED
  >

=== shmuelp/asiddur/trunk/texts/davidovici/tefillot-annotated.xml
<?xml version="1.0" encoding="windows-1255"?>
<!DOCTYPE asiddur-annotated SYSTEM "../../tools/asiddur-tefilla-annotated.dtd">
<asiddur-annotated format="0.1"><toc><texts><text-header name="chatzi-kaddish" id="1" length="474"/><text-header name="kaddish-end" id="2" length="197"/><text-header name="kaddish-shalem" id="3" length="110"/><text-header name="kaddish-yasom" id="4" length="26"/><text-header name="shma" id="5" length="2128"/><text-header name="amidah" id="6" length="8156"/><text-header name="aleinu" id="7" length="1592"/><text-header name="ldavid" id="8" length="1111"/><text-header name="lamnatzeiach" id="9" length="1200"/><text-header name="maariv" id="10" length="9627"/></texts><tefillot><tefilla target="maariv">
			<name lang="en">Ma'ariv</name>
			<name lang="he">מעריב</name>
		</tefilla></tefillot></toc><text name="chatzi-kaddish" length="474">
יִתְגַּדַּל וְיִתְקַדַּשׁ שְׁמֵהּ רַבָּא. בְּעָלְמָא דִּי בְרָא כִרְעוּתֵהּ, וְיַמְלִיךְ מַלְכוּתֵהּ בְּחַיֵּיכוֹן וּבְיוֹמֵיכוֹן וּבְחַיֵּי דְכָל בֵּית יִשְׂרָאֵל, בַּעֲגָלָא וּבִזְמַן קָרִיב, וְאִמְרוּ אָמֵן. יְהֵא שְׁמֵהּ רַבָּא מְבָרַךְ לְעָלַם וּלְעָלְמֵי עָלְמַיָּא.
יִתְבָּרַךְ וְיִשְׁתַּבַּח וְיִתְפָּאַר וְיִתְרוֹמַם וְיִתְנַשֵּׂא וְיִתְהַדָּר וְיִתְעַלֶּה וְיִתְהַלָּל שְׁמֵהּ דְּקֻדְשָׁא בְּרִיךְ הוּא, לְעֵֽלָּא <if function="IN_ASERET_YIMAY_TESHUVA" length="19">וּלְעֵֽלָּא מִ<else/>מִן </if>כָּל בִּרְכָתָא וְשִׁירָתָא תֻּשְׁבְּחָתָא וְנֶחֱמָתָא, דַּאֲמִירָן בְּעָלְמָא, וְאִמְרוּ אָמֵן.
	</text><text name="kaddish-end" length="197">
יְהֵא שְׁלָמָא רַבָּא מִן שְׁמַיָּא, וְחַיִּים )טוֹבִים( עָלֵֽינוּ וְעַל כָּל יִשְׂרָאֵל, וְאִמְרוּ אָמֵן.
עֹשֶׂה שָׁלוֹם <if function="IN_ASERET_YIMAY_TESHUVA" length="10">(הַשָּׁלוֹם) </if>בִּמְרוֹמָיו, הוּא יַעֲשֶׂה שָׁלוֹם עָלֵֽינוּ וְעַל כָּל יִשְׂרָאֵל, וְאִמְרוּ אָמֵן.
	</text><text name="kaddish-shalem" length="110">
		<include target="chatzi-kaddish"/>
תִּתְקַבֵּל צְלוֹתְהוֹן וּבָעוּתְהוֹן דְּכָל )בֵּית( יִשְׂרָאֵל קֳדָם אֲבוּהוֹן דִּי בִשְׁמַיָּא וְאִמְרוּ אָמֵן.
		<include target="kaddish-end"/>
	</text><text name="kaddish-yasom" length="26">            
		<include target="chatzi-kaddish"/>
		<include target="kaddish-end"/>
	</text><text name="shma" length="2128">
שְׁמַע | יִשְׂרָאֵל, יְיָ | אֱלֹהֵֽינוּ, יְיָ | אֶחָד.
בָּרוּךְ שֵׁם כְּבוֹד מַלְכוּתוֹ לְעוֹלָם וָעֶד.
<br/>
וְאָהַבְתָּ אֵת יְיָ | אֱלֹהֶֽיךָ, בְּכָל | לְבָבְךָ, וּבְכָל נַפְשְׁךָ, וּבְכָל מְאֹדֶֽךָ. וְהָיוּ הַדְּבָרִים הָאֵֽלֶּה, אֲשֶׁר | אָנֹכִי מְצַוְּךָ הַיּוֹם, עַל | לְבָבֶֽךָ. וְשִׁנַּנְתָּם לְבָנֶֽיךָ, וְדִבַּרְתָּ בָּם, בְּשִׁבְתְּךָ בְּבֵיתֶֽךָ, וּבְלֶכְתְּךָ בַדֶּֽרֶךְ, וּבְשָׁכְבְּךָ, וּבְקוּמֶֽךָ. וּקְשַׁרְתָּם לְאוֹת | עַל יָדֶֽךָ, וְהָיוּ לְטֹטָפֹת בֵּין | עֵינֶֽיךָ. וּכְתַבְתָּם | עַל מְזֻזוֹת בֵּיתֶֽךָ וּבִשְׁעָרֶֽיךָ.
<br/>
וְהָיָה אִם שָׁמֹֽעַ תִּשְׁמְעוּ אֶל מִצְוֹתַי, אֲשֶׁר | אָנֹכִי מְצַוֶּה | אֶתְכֶם הַיּוֹם, לְאַהֲבָה אֶת יְיָ | אֱלֹהֵיכֶם וּלְעָבְדוֹ, בְּכָל | לְבַבְכֶם וּבְכָל נַפְשְׁכֶם. וְנָתַתִּי מְטַר | אַרְצְכֶם בְּעִתּוֹ, יוֹרֶה וּמַלְקוֹשׁ, וְאָסַפְתָּ דְגָנֶֽךָ וְתִירֹשְׁךָ וְיִצְהָרֶֽךָ. וְנָתַתִּי | עֵֽשֶׂב | בְּשָׂדְךָ לִבְהֶמְתֶּֽךָ, וְאָכַלְתָּ וְשָׂבָֽעְתָּ. הִשָּׁמְרוּ לָכֶם פֶּן יִפְתֶּה לְבַבְכֶם, וְסַרְתֶּם וַעֲבַדְתֶּם | אֱלֹהִים | אֲחֵרִים וְהִשְׁתַּחֲוִיתֶם לָהֶם. וְחָרָה | אַף יְיָ בָּכֶם, וְעָצַר | אֶת הַשָּׁמַֽיִם וְלֹא יִהְיֶה מָטָר, וְהָאֲדָמָה לֹא תִתֵּן אֶת יְבוּלָהּ, וַאֲבַדְתֶּם | מְהֵרָה מֵעַל הָאָֽרֶץ הַטֹּבָה | אֲשֶׁר | יְיָ נֹתֵן לָכֶם. וְשַׂמְתֶּם | אֶת דְּבָרַי | אֵֽלֶּה עַל | לְבַבְכֶם וְעַל נַפְשְׁכֶם, וּקְשַׁרְתֶּם | אֹתָם לְאוֹת | עַל יֶדְכֶם, וְהָיוּ לְטוֹטָפֹת בֵּין | עֵינֵיכֶם. וְלִמַּדְתֶּם | אֹתָם | אֶת בְּנֵיכֶם לְדַבֵּר בָּם, בְּשִׁבְתְּךָ בְּבֵיתֶֽךָ, וּבְלֶכְתְּךָ בַדֶּֽרֶךְ, וּבְשָׁכְבְּךָ, וּבְקוּמֶֽךָ. וּכְתַבְתָּם | עַל מְזוּזוֹת בֵּיתֶֽךָ וּבִשְׁעָרֶֽיךָ. לְמַֽעַן | יִרְבּוּ | יְמֵיכֶם וִימֵי בְנֵיכֶם | עַל הָאֲדָמָה | אֲשֶׁר נִשְׁבַּע | יְיָ לַאֲבֹתֵיכֶם לָתֵת לָהֶם, כִּימֵי הַשָּׁמַֽיִם | עַל הָאָֽרֶץ.
<br/>
וַיֹּֽאמֶר | יְיָ | אֶל מֹשֶׁה לֵּאמֹר. דַּבֵּר | אֶל בְּנֵי | יִשְׂרָאֵל וְאָמַרְתָּ אֲלֵהֶם, וְעָשׂוּ לָהֶם צִיצִת עַל כַּנְפֵי בִגְדֵיהֶם לְדֹרֹתָם, וְנָתְנוּ | עַל צִיצִת הַכָּנָף פְּתִיל תְּכֵֽלֶת. וְהָיָה לָכֶם לְצִיצִת, וּרְאִיתֶם | אֹתוֹ וּזְכַרְתֶּם | אֶת כָּל מִצְוֹת | יְיָ, וַעֲשִׂיתֶם | אֹתָם, וְלֹא תָתֽוּרוּ | אַחֲרֵי לְבַבְכֶם וְאַחֲרֵי | עֵינֵיכֶם, אֲשֶׁר אַתֶּם זֹנִים | אַחֲרֵיהֶם. לְמַֽעַן תִּזְכְּרוּ וַעֲשִׂיתֶם | אֶת כָּל מִצְוֹתָי, וִהְיִיתֶם קְדֹשִׁים לֵאלֹהֵיכֶם. אֲנִי יְיָ | אֱלֹהֵיכֶם, אֲשֶׁר הוֹצֵֽאתִי | אֶתְכֶם | מֵאֶֽרֶץ מִצְרַֽיִם, לִהְיוֹת לָכֶם לֵאלֹהִים, אֲנִי | יְיָ | אֱלֹהֵיכֶם. אֱמֶת-
	</text><text name="amidah" length="8156">
אֲדֹנָי שְׂפָתַי תִּפְתָּח וּפִי יַגִּיד תְּהִלָּתֶֽךָ.
בָּרוּךְ אַתָּה יְיָ אֱלֹהֵֽינוּ וֵאלֹהֵי אֲבוֹתֵֽינוּ, אֱלֹהֵי אַבְרָהָם, אֱלֹהֵי יִצְחָק, וֵאלֹהֵי יַעֲקֹב, הָאֵל הַגָּדוֹל הַגִּבּוֹר וְהַנּוֹרָא, אֵל עֶלְיוֹן, גּוֹמֵל חֲסָדִים טוֹבִים, וְקֹנֵה הַכֹּל, וְזוֹכֵר חַסְדֵי אָבוֹת, וּמֵבִיא גוֹאֵל לִבְנֵי בְנֵיהֶם, לְמַֽעַן שְׁמוֹ בְּאַהֲבָה.
<if function="IN_ASERET_YIMAY_TESHUVA" length="102">זָכְרֵֽנוּ לְחַיִּים, מֶֽלֶךְ חָפֵץ בַּחַיִּים, וְכָתְבֵֽנוּ בְּסֵֽפֶר הַחַיִּים, לְמַעַנְךָ אֱלֹהִים חַיִּים.</if>
מֶֽלֶךְ עוֹזֵר וּמוֹשִֽׁיעַ וּמָגֵן. בָּרוּךְ אַתָּה יְיָ, מָגֵן אַבְרָהָם.
<br/>
אַתָּה גִּבּוֹר לְעוֹלָם אֲדֹנָי, מְחַיֵּה מֵתִים אַֽתָּה, רַב לְהוֹשִֽׁיעַ.
<if function="SUKKOT_TO_PESACH" length="50">מַשִּׁיב הָרֽוּחַ וּמוֹרִיד הַגֶּֽשֶׁם<else/><if variable="MORID_HATAL" length="12">מוֹרִיד הַטַּל</if></if>
מְכַלְכֵּל חַיִּים בְּחֶֽסֶד, מְחַיֵּה מֵתִים בְּרַחֲמִים רַבִּים, סוֹמֵךְ נוֹפְלִים, וְרוֹפֵא חוֹלִים, וּמַתִּיר אֲסוּרִים, וּמְקַיֵּם אֱמוּנָתוֹ לִישֵׁנֵי עָפָר, מִי כָמֽוֹךָ בַּֽעַל גְּבוּרוֹת וּמִי דּֽוֹמֶה לָּךְ, מֶֽלֶךְ מֵמִית וּמְחַיֶּה וּמַצְמִֽיחַ יְשׁוּעָה. 
<if function="IN_ASERET_YIMAY_TESHUVA" length="61">מִי כָמוֹךָ אַב הָרַחֲמִים, זוֹכֵר יְצוּרָיו לְחַיִּים בְּרַחֲמִים.</if>
וְנֶאֱמָן אַתָּה לְהַחֲיוֹת מֵתִים. בָּרוּךְ אַתָּה יְיָ, מְחַיֵּה הַמֵּתִים.
<br/>
אַתָּה קָדוֹשׁ וְשִׁמְךָ קָדוֹשׁ, וּקְדוֹשִׁים בְּכָל יוֹם יְהַלְלֽוּךָ סֶּֽלָה. בָּרוּךְ אַתָּה יְיָ, <if function="IN_ASERET_YIMAY_TESHUVA" length="33">הַמֶּֽלֶךְ הַקָּדוֹשׁ<else/>הָאֵל הַקָּדוֹשׁ</if>.
<br/>
אַתָּה חוֹנֵן לְאָדָם דַּֽעַת, וּמְלַמֵּד לֶאֱנוֹשׁ בִּינָה. חָנֵּֽנוּ מֵאִתְּךָ דֵּעָה, בִּינָה וְהַשְׂכֵּל. בָּרוּךְ אַתָּה יְיָ, חוֹנֵן הַדָּעַת.
<br/>
הֲשִׁיבֵֽנוּ אָבִֽינוּ לְתוֹרָתֶֽךָ, וְקָרְבֵֽנוּ מַלְכֵּֽנוּ לַעֲבוֹדָתֶֽךָ, וְהַחֲזִירֵֽנוּ בִּתְשׁוּבָה שְׁלֵמָה לְפָנֶֽיךָ. בָּרוּךְ אַתָּה יְיָ, הָרוֹצֶה בִּתְשׁוּבָה.
<br/>
סְלַח לָֽנוּ, אָבִֽינוּ, כִּי חָטָֽאנוּ, מְחַל לָֽנוּ, מַלְכֵּֽנוּ, כִּי פָשָֽׁעְנוּ, כִּי מוֹחֵל וְסוֹלֵֽחַ אָֽתָּה. בָּרוּךְ אַתָּה יְיָ, חַנּוּן הַמַּרְבֶּה לִסְלֹֽחַ. 
<br/>
רְאֵה בְעָנְיֵֽנוּ, וְרִֽיבָה רִיבֵֽנוּ, וּגְאָלֵֽנוּ מְהֵרָה לְמַֽעַן שְׁמֶֽךָ, כִּי גּוֹאֵל חָזָק אָֽתָּה. בָּרוּךְ אַתָּה יְיָ, גּוֹאֵל יִשְׂרָאֵל.
<br/>
רְפָאֵֽנוּ, יְיָ, וְנֵרָפֵא, הוֹשִׁיעֵֽנוּ וְנִוָּשֵֽׁעָה, כִּי תְהִלָּתֵֽנוּ אָֽתָּה, וְהַעֲלֵה רְפוּאָה שְׁלֵמָה לְכָל מַכּוֹתֵֽינוּ. כִּי אֵל מֶֽלֶךְ רוֹפֵא נֶאֱמָן וְרַחֲמָן אָתָּה. בָּרוּךְ אַתָּה יְיָ, רוֹפֵא חוֹלֵי עַמוֹ יִשְׂרָאֵל.
<br/>
בָּרֵךְ עָלֵֽינוּ, יְיָ אֱלֹהֵֽינוּ, אֶת הַשָּׁנָה הַזֹּאת וְאֶת כָּל מִינֵי תְבוּאָתָהּ לְטוֹבָה, וְתֵן <if function="SAY_TAL_UMATAR" length="20">טַל וּמָטָר לִבְ<else/>בְּ</if>רָכָה, עַל פְּנֵי הָאֲדָמָה, וְשַׂבְּעֵֽנוּ מִטּוּבֶֽךָ, וּבָרֵךְ שְׁנָתֵֽנוּ כַּשָּׁנִים הַטּוֹבוֹת. בָּרוּךְ אַתָּה יְיָ, מְבָרֵךְ הַשָּׁנִים.
<br/>
תְּקַע בְּשׁוֹפָר גָּדוֹל לְחֵרוּתֵֽנוּ, וְשָׂא נֵס לְקַבֵּץ גָּלֻיּוֹתֵֽינוּ, וְקַבְּצֵֽנוּ יַֽחַד מֵאַרְבַּע כַּנְפוֹת הָאָֽרֶץ. בָּרוּךְ אַתָּה יְיָ, מְקַבֵּץ נִדְחֵי עַמוֹ יִשְׂרָאֵל.
<br/>
הָשִֽׁיבָה שׁוֹפְטֵֽינוּ כְּבָרִאשׁוֹנָה וְיוֹעֲצֵֽינוּ כְּבַתְּחִלָּה, וְהָסֵר מִמֶּֽנּוּ יָגוֹן וַאֲנָחָה, וּמְלוֹךְ עָלֵֽינוּ אַתָּה, יְיָ, לְבַדְּךָ בְּחֶֽסֶד וּבְרַחֲמִים, וְצַדְּקֵֽנוּ בַּמִּשְׁפָּט. בָּרוּךְ אַתָּה יְיָ, <if function="IN_ASERET_YIMAY_TESHUVA" length="52">הַמֶּֽלֶךְ הַמִּשְׁפָּט<else/>מֶֽלֶךְ אוֹהֵב צְדָקָה וּמִשְׁפָּט</if>.
<br/>
וְלַמַּלְשִׁינִים אַל תְּהִי תִקְוָה, וְכָל הָרִשְׁעָה כְּרֶֽגַע תֹּאבֵד, וְכָל אוֹיְבֶֽיךָ מְהֵרָה יִכָּרֵֽתוּ, וְהַזֵּדִים מְהֵרָה תְעַקֵּר וּתְשַׁבֵּר וּתְמַגֵּר וְתַכְנִֽיעַ בִּמְהֵרָה בְיָמֵֽינוּ. בָּרוּךְ אַתָּה יְיָ, שֹׁבֵר אֹיְבִים וּמַכְנִֽיעַ זֵדִים.
<br/>
עַל הַצַּדִּיקִים וְעַל הַחֲסִידִים וְעַל זִקְנֵי עַמְּךָ בֵּית יִשְׂרָאֵל, וְעַל פְּלֵיטַת סוֹפְרֵיהֶם, וְעַל גֵּרֵי הַצֶּֽדֶק וְעָלֵֽינוּ, יֶהֱמוּ נָא רַחֲמֶֽיךָ, יְיָ אֱלֹהֵֽינוּ, וְתֵן שָׂכָר טוֹב לְכָל הַבּוֹטְחִים בְּשִׁמְךָ בֶּאֱמֶת, וְשִׂים חֶלְקֵֽנוּ עִמָּהֶם לְעוֹלָם, וְלֹא נֵבוֹשׁ כִּי בְךָ בָּטָֽחְנוּ. בָּרוּךְ אַתָּה יְיָ, מִשְׁעָן וּמִבְטָח לַצַּדִּיקִים.
<br/>
וְלִירוּשָׁלַֽיִם עִירְךָ בְּרַחֲמִים תָּשׁוּב, וְתִשְׁכּוֹן בְּתוֹכָהּ כַּאֲשֶׁר דִּבַּֽרְתָּ, וּבְנֵה אוֹתָהּ בְּקָרוֹב בְּיָמֵֽינוּ בִּנְיַן עוֹלָם, וְכִסֵּא דָוִד מְהֵרָה לְתוֹכָהּ תָּכִין. בָּרוּךְ אַתָּה יְיָ, בּוֹנֵה יְרוּשָׁלָֽיִם.
<br/>
אֶת צֶֽמַח דָּוִד עַבְדְּךָ מְהֵרָה תַצְמִֽיחַ, וְקַרְנוֹ תָּרוּם בִּישׁוּעָתֶֽךָ, כִּי לִישׁוּעָתְךָ קִוִּֽינוּ כָּל הַיּוֹם. בָּרוּךְ אַתָּה יְיָ, מַצְמִֽיחַ קֶֽרֶן יְשׁוּעָה. 
<br/>
שְׁמַע קוֹלֵֽנוּ, יְיָ אֱלֹהֵֽינוּ, חוּס וְרַחֵם עָלֵֽינוּ, וְקַבֵּל בְּרַחֲמִים וּבְרָצוֹן אֶת תְּפִלָּתֵֽנוּ, כִּי אֵל שׁוֹמֵֽעַ תְּפִלּוֹת וְתַחֲנוּנִים אָֽתָּה, וּמִלְּפָנֶֽיךָ, מַלְכֵּֽנוּ, רֵיקָם אַל תְּשִׁיבֵֽנוּ. כִּי אַתָּה שׁוֹמֵֽעַ תְּפִלַּת עַמְּךָ יִשְׂרָאֵל בְּרַחֲמִים. בָּרוּךְ אַתָּה יְיָ, שׁוֹמֵֽעַ תְּפִלָּה.
<br/>
רְצֵה, יְיָ אֱלֹהֵֽינוּ, בְּעַמְּךָ יִשְׂרָאֵל וּבִתְפִלָּתָם, וְהָשֵׁב אֶת הָעֲבוֹדָה לִדְבִיר בֵּיתֶֽךָ, וְאִשֵּׁי יִשְׂרָאֵל, וּתְפִלָּתָם בְּאַהֲבָה תְקַבֵּל בְּרָצוֹן, וּתְהִי לְרָצוֹן תָּמִיד עֲבוֹדַת יִשְׂרָאֵל עַמֶּֽךָ.
<if function="SAY_YAALEH_VYAVOH" length="646">
<navmark/>
<br/>
